/**
 * Tabela CID-10 — códigos mais comuns em atestados, afastamentos e saúde ocupacional no Brasil
 * Cobre todos os capítulos relevantes: A-B (infecciosas), C-D (neoplasias/sangue),
 * E (endócrinas), F (mental), G (neurológico), H (olho/ouvido), I (circulatório),
 * J (respiratório), K (digestivo), L (pele), M (musculoesquelético), N (gênito-urinário),
 * O (gravidez), R (sintomas), S-T (lesões), Z (fatores/ocupacionais)
 */
export const CID10 = [
  // ── A: Doenças Infecciosas Intestinais ──────────────────────────────────
  ["A00","Cólera"],
  ["A01","Febres tifóide e paratifóide"],
  ["A02","Outras infecções por Salmonella"],
  ["A03","Shigelose"],
  ["A04","Outras infecções intestinais bacterianas"],
  ["A05","Outras intoxicações alimentares de origem bacteriana"],
  ["A06","Amebíase"],
  ["A08","Infecções intestinais virais e outras especificadas"],
  ["A09","Diarréia e gastroenterite de origem infecciosa presumível"],
  ["A09.0","Gastroenterite infecciosa de origem não especificada"],

  // ── A: Tuberculose ────────────────────────────────────────────────────────
  ["A15","Tuberculose respiratória confirmada bacteriologicamente"],
  ["A16","Tuberculose respiratória sem confirmação bacteriológica"],
  ["A17","Tuberculose do sistema nervoso"],
  ["A18","Tuberculose de outros órgãos"],
  ["A19","Tuberculose miliar"],

  // ── A: Outras doenças bacterianas ─────────────────────────────────────────
  ["A36","Difteria"],
  ["A37","Coqueluche"],
  ["A38","Escarlatina"],
  ["A39","Infecção meningocócica"],
  ["A40","Septicemia estreptocócica"],
  ["A41","Outra septicemia"],
  ["A46","Erisipela"],
  ["A49","Infecção bacteriana de localização não especificada"],

  // ── A: Doenças transmitidas por vetores ──────────────────────────────────
  ["A50","Sífilis congênita"],
  ["A51","Sífilis precoce"],
  ["A52","Sífilis tardia"],
  ["A53","Outras formas e as não especificadas de sífilis"],
  ["A54","Infecção gonocócica"],
  ["A55","Linfogranuloma por clamídia"],
  ["A56","Outras doenças sexualmente transmissíveis por clamídias"],
  ["A60","Infecção anogenital pelo vírus do herpes humano"],
  ["A63","Outras doenças de transmissão predominantemente sexual"],
  ["A77","Febre maculosa"],
  ["A90","Dengue clássica"],
  ["A91","Febre hemorrágica devida ao vírus do dengue"],
  ["A92","Outras febres virais transmitidas por mosquitos"],
  ["A95","Febre amarela"],
  ["A98","Outras febres virais hemorrágicas"],

  // ── B: Doenças virais ─────────────────────────────────────────────────────
  ["B00","Infecções pelo vírus do herpes simples"],
  ["B00.1","Dermatite vesicular herpética"],
  ["B01","Varicela"],
  ["B01.9","Varicela sem complicação"],
  ["B02","Herpes zóster"],
  ["B02.9","Herpes zóster sem complicação"],
  ["B03","Varíola"],
  ["B04","Varíola dos macacos"],
  ["B05","Sarampo"],
  ["B06","Rubéola"],
  ["B06.9","Rubéola sem complicação"],
  ["B07","Verrugas de origem viral"],
  ["B08","Outras infecções virais caracterizadas por lesões cutâneas"],
  ["B09","Infecção viral não especificada caracterizada por lesões cutâneas"],
  ["B10","Outras infecções por herpesvírus humano"],
  ["B15","Hepatite aguda A"],
  ["B16","Hepatite aguda B"],
  ["B17","Outras hepatites virais agudas"],
  ["B18","Hepatite viral crônica"],
  ["B19","Hepatite viral não especificada"],
  ["B20","Doença pelo HIV resultando em doenças infecciosas e parasitárias"],
  ["B21","Doença pelo HIV resultando em neoplasias malignas"],
  ["B22","Doença pelo HIV resultando em outras doenças especificadas"],
  ["B23","Doença pelo HIV resultando em outras afecções"],
  ["B24","Doença pelo vírus da imunodeficiência humana não especificada"],
  ["B25","Doença por citomegalovírus"],
  ["B26","Caxumba (parotidite epidêmica)"],
  ["B27","Mononucleose infecciosa"],
  ["B27.9","Mononucleose infecciosa não especificada"],
  ["B30","Conjuntivite viral"],
  ["B33","Outras doenças virais"],
  ["B34","Doença viral de localização não especificada"],
  ["B34.0","Infecção pelo adenovírus de localização não especificada"],
  ["B34.1","Infecção pelo enterovírus de localização não especificada"],
  ["B34.2","Infecção pelo coronavírus de localização não especificada"],
  ["B34.8","Outras infecções virais de localização não especificada"],
  ["B34.9","Infecção viral não especificada"],
  ["B35","Dermatofitose"],
  ["B36","Outras micoses superficiais"],
  ["B37","Candidíase"],
  ["B37.0","Estomatite candidiásica"],
  ["B37.3","Candidíase da vulva e da vagina"],
  ["B37.9","Candidíase não especificada"],
  ["B44","Aspergilose"],
  ["B49","Micose não especificada"],
  ["B54","Malária não especificada"],
  ["B65","Esquistossomose"],
  ["B76","Ancilostomíase"],
  ["B77","Ascaridíase"],
  ["B79","Tricuríase"],
  ["B80","Oxiuríase"],
  ["B82","Parasitoses intestinais mistas"],
  ["B85","Pediculose e ftiríase"],
  ["B86","Escabiose (Sarna)"],
  ["B99","Outras doenças infecciosas e as não especificadas"],

  // ── C: Neoplasias malignas ─────────────────────────────────────────────────
  ["C00","Neoplasia maligna do lábio"],
  ["C02","Neoplasia maligna de outras partes e de partes não especificadas da língua"],
  ["C15","Neoplasia maligna do esôfago"],
  ["C16","Neoplasia maligna do estômago"],
  ["C18","Neoplasia maligna do cólon"],
  ["C20","Neoplasia maligna do reto"],
  ["C22","Neoplasia maligna do fígado"],
  ["C25","Neoplasia maligna do pâncreas"],
  ["C33","Neoplasia maligna da traquéia"],
  ["C34","Neoplasia maligna dos brônquios e dos pulmões"],
  ["C43","Melanoma maligno da pele"],
  ["C44","Outras neoplasias malignas da pele"],
  ["C50","Neoplasia maligna da mama"],
  ["C53","Neoplasia maligna do colo do útero"],
  ["C54","Neoplasia maligna do corpo do útero"],
  ["C56","Neoplasia maligna do ovário"],
  ["C61","Neoplasia maligna da próstata"],
  ["C67","Neoplasia maligna da bexiga"],
  ["C73","Neoplasia maligna da glândula tireóide"],
  ["C80","Neoplasia maligna sem especificação de localização"],
  ["C85","Outros linfomas não-Hodgkin e os não especificados"],
  ["C90","Mieloma múltiplo e neoplasias malignas de plasmócitos"],
  ["C91","Leucemia linfóide"],
  ["C92","Leucemia mielóide"],

  // ── D: Doenças do sangue ───────────────────────────────────────────────────
  ["D50","Anemia por deficiência de ferro"],
  ["D50.9","Anemia por deficiência de ferro não especificada"],
  ["D51","Anemia por deficiência de vitamina B12"],
  ["D52","Anemia por deficiência de folato"],
  ["D53","Outras anemias nutricionais"],
  ["D55","Anemia devida a transtornos enzimáticos"],
  ["D56","Talassemia"],
  ["D57","Transtornos falciformes"],
  ["D58","Outras anemias hemolíticas hereditárias"],
  ["D60","Aplasia adquirida exclusiva da série vermelha"],
  ["D61","Outras anemias aplásticas"],
  ["D64","Outras anemias"],
  ["D64.9","Anemia não especificada"],
  ["D65","Coagulação intravascular disseminada"],
  ["D69","Púrpura e outras afecções hemorrágicas"],
  ["D70","Agranulocitose"],
  ["D72","Outros transtornos dos leucócitos"],

  // ── E: Doenças endócrinas e metabólicas ──────────────────────────────────
  ["E00","Síndrome de deficiência congênita de iodo"],
  ["E01","Transtornos tireoidianos e afins relacionados à deficiência de iodo"],
  ["E03","Outro hipotireoidismo"],
  ["E03.9","Hipotireoidismo não especificado"],
  ["E04","Bócio não tóxico"],
  ["E05","Tireotoxicose"],
  ["E06","Tireoidite"],
  ["E10","Diabetes mellitus insulino-dependente"],
  ["E11","Diabetes mellitus não-insulino-dependente"],
  ["E11.0","Diabetes mellitus tipo 2 com coma"],
  ["E11.4","Diabetes mellitus tipo 2 com complicações neurológicas"],
  ["E11.5","Diabetes mellitus tipo 2 com complicações circulatórias periféricas"],
  ["E11.9","Diabetes mellitus tipo 2 sem complicações"],
  ["E14","Diabetes mellitus não especificado"],
  ["E20","Hipoparatireoidismo"],
  ["E21","Hiperparatireoidismo"],
  ["E27","Outros transtornos da glândula supra-renal"],
  ["E28","Disfunção ovariana"],
  ["E29","Disfunção testicular"],
  ["E40","Kwashiorkor"],
  ["E41","Marasmo nutricional"],
  ["E46","Desnutrição protéico-calórica não especificada"],
  ["E55","Deficiência de vitamina D"],
  ["E58","Deficiência dietética de cálcio"],
  ["E61","Deficiência de outros elementos nutritivos"],
  ["E63","Outras deficiências nutricionais"],
  ["E65","Adiposidade localizada"],
  ["E66","Obesidade"],
  ["E66.0","Obesidade devida a excesso de calorias"],
  ["E66.9","Obesidade não especificada"],
  ["E72","Outros transtornos do metabolismo dos aminoácidos"],
  ["E78","Transtornos do metabolismo das lipoproteínas e outras lipidemias"],
  ["E78.0","Hipercolesterolemia pura"],
  ["E78.1","Hipertrigliceridemia pura"],
  ["E78.5","Hiperlipidemia não especificada"],
  ["E83","Transtornos do metabolismo de minerais"],
  ["E87","Outros transtornos do equilíbrio hidroeletrolítico e ácido-básico"],

  // ── F: Transtornos Mentais ─────────────────────────────────────────────────
  ["F00","Demência na doença de Alzheimer"],
  ["F01","Demência vascular"],
  ["F10","Transtornos mentais e comportamentais pelo uso de álcool"],
  ["F10.1","Uso nocivo de álcool"],
  ["F10.2","Síndrome de dependência do álcool"],
  ["F11","Transtornos pelo uso de opioides"],
  ["F17","Transtornos pelo uso de tabaco"],
  ["F17.1","Uso nocivo do tabaco"],
  ["F17.2","Síndrome de dependência do tabaco"],
  ["F19","Transtornos mentais pelo uso de múltiplas drogas"],
  ["F20","Esquizofrenia"],
  ["F31","Transtorno afetivo bipolar"],
  ["F31.0","Transtorno afetivo bipolar, episódio atual hipomaníaco"],
  ["F31.1","Transtorno afetivo bipolar, episódio atual maníaco sem sintomas psicóticos"],
  ["F32","Episódio depressivo"],
  ["F32.0","Episódio depressivo leve"],
  ["F32.1","Episódio depressivo moderado"],
  ["F32.2","Episódio depressivo grave sem sintomas psicóticos"],
  ["F32.3","Episódio depressivo grave com sintomas psicóticos"],
  ["F32.9","Episódio depressivo não especificado"],
  ["F33","Transtorno depressivo recorrente"],
  ["F33.0","Transtorno depressivo recorrente — episódio atual leve"],
  ["F33.1","Transtorno depressivo recorrente — episódio atual moderado"],
  ["F33.2","Transtorno depressivo recorrente — episódio atual grave"],
  ["F40","Transtornos fóbico-ansiosos"],
  ["F41","Outros transtornos ansiosos"],
  ["F41.0","Transtorno de pânico"],
  ["F41.1","Ansiedade generalizada"],
  ["F41.2","Transtorno misto ansioso e depressivo"],
  ["F43","Reações ao estresse grave e transtornos de adaptação"],
  ["F43.0","Reação aguda ao estresse"],
  ["F43.1","Transtorno de estresse pós-traumático"],
  ["F43.2","Transtornos de adaptação"],
  ["F44","Transtornos dissociativos"],
  ["F45","Transtornos somatoformes"],
  ["F48","Outros transtornos neuróticos"],
  ["F48.0","Neurastenia (Burnout / Síndrome de esgotamento)"],
  ["F50","Transtornos alimentares"],
  ["F51","Transtornos do sono não orgânicos"],
  ["F51.0","Insônia não orgânica"],
  ["F60","Transtornos específicos de personalidade"],

  // ── G: Sistema Nervoso ────────────────────────────────────────────────────
  ["G20","Doença de Parkinson"],
  ["G30","Doença de Alzheimer"],
  ["G40","Epilepsia"],
  ["G43","Enxaqueca"],
  ["G44","Outras cefaléias"],
  ["G45","Ataques isquêmicos transitórios"],
  ["G47","Transtornos do sono"],
  ["G47.0","Distúrbios do início e da manutenção do sono (insônias)"],
  ["G47.3","Apnéia de sono"],
  ["G51","Transtornos do nervo facial"],
  ["G51.0","Paralisia de Bell"],
  ["G54","Transtornos das raízes e plexos nervosos"],
  ["G54.2","Síndrome da raiz cervical"],
  ["G56","Mononeuropatias do membro superior"],
  ["G56.0","Síndrome do túnel do carpo"],
  ["G56.2","Lesão do nervo ulnar"],
  ["G57","Mononeuropatias do membro inferior"],
  ["G62","Outras polineuropatias"],

  // ── H: Olho e Ouvido ─────────────────────────────────────────────────────
  ["H01","Outras inflamações da pálpebra"],
  ["H10","Conjuntivite"],
  ["H10.9","Conjuntivite não especificada"],
  ["H11","Outros transtornos da conjuntiva"],
  ["H16","Ceratite"],
  ["H25","Catarata senil"],
  ["H26","Outras cataratas"],
  ["H40","Glaucoma"],
  ["H52","Distúrbios da refração e da acomodação"],
  ["H60","Otite externa"],
  ["H65","Otite média não-supurativa"],
  ["H66","Otite média supurativa"],
  ["H66.9","Otite média não especificada"],
  ["H72","Perfuração da membrana do tímpano"],
  ["H83","Outras doenças do ouvido interno"],
  ["H83.3","Efeitos de ruído sobre o ouvido (PAIR)"],
  ["H90","Perda de audição por transtorno de condução e neuro-sensorial"],
  ["H91","Outras perdas de audição"],
  ["H91.9","Perda de audição não especificada"],

  // ── I: Aparelho Circulatório ─────────────────────────────────────────────
  ["I10","Hipertensão essencial (primária)"],
  ["I11","Doença cardíaca hipertensiva"],
  ["I20","Angina pectoris"],
  ["I20.0","Angina instável"],
  ["I21","Infarto agudo do miocárdio"],
  ["I25","Doença isquêmica crônica do coração"],
  ["I26","Embolia pulmonar"],
  ["I42","Cardiomiopatia"],
  ["I48","Fibrilação e flutter atrial"],
  ["I49","Outras arritmias cardíacas"],
  ["I50","Insuficiência cardíaca"],
  ["I63","Infarto cerebral"],
  ["I64","Acidente vascular cerebral — AVC"],
  ["I70","Aterosclerose"],
  ["I80","Flebite e tromboflebite"],
  ["I83","Varizes dos membros inferiores"],
  ["I84","Hemorroidas"],

  // ── J: Aparelho Respiratório ─────────────────────────────────────────────
  ["J00","Nasofaringite aguda (resfriado comum)"],
  ["J01","Sinusite aguda"],
  ["J01.9","Sinusite aguda não especificada"],
  ["J02","Faringite aguda"],
  ["J02.9","Faringite aguda não especificada"],
  ["J03","Amigdalite aguda"],
  ["J03.9","Amigdalite aguda não especificada"],
  ["J04","Laringite e traqueíte agudas"],
  ["J06","Infecções agudas das vias aéreas superiores"],
  ["J06.9","Infecção aguda das vias aéreas superiores não especificada"],
  ["J10","Gripe devida a vírus da influenza identificado"],
  ["J11","Gripe devida a vírus não identificado"],
  ["J11.0","Pneumonia gripal"],
  ["J11.1","Gripe com outras manifestações respiratórias"],
  ["J12","Pneumonia viral"],
  ["J13","Pneumonia devida ao Streptococcus pneumoniae"],
  ["J15","Pneumonia bacteriana"],
  ["J18","Pneumonia por microrganismo não especificado"],
  ["J18.9","Pneumonia não especificada"],
  ["J20","Bronquite aguda"],
  ["J20.9","Bronquite aguda não especificada"],
  ["J30","Rinite alérgica e vasomotora"],
  ["J31","Rinite, nasofaringite e faringite crônicas"],
  ["J32","Sinusite crônica"],
  ["J35","Doenças crônicas das amígdalas e adenoides"],
  ["J40","Bronquite não especificada"],
  ["J44","Outras doenças pulmonares obstrutivas crônicas"],
  ["J45","Asma"],
  ["J45.0","Asma predominantemente alérgica"],
  ["J45.1","Asma não alérgica"],
  ["J45.9","Asma não especificada"],
  ["J60","Pneumoconiose dos mineiros de carvão"],
  ["J61","Pneumoconiose devida ao amianto"],
  ["J62","Pneumoconiose devida a poeira de sílica"],

  // ── K: Aparelho Digestivo ─────────────────────────────────────────────────
  ["K02","Cárie dentária"],
  ["K04","Doenças da polpa e dos tecidos periapicais"],
  ["K05","Gengivite e doenças periodontais"],
  ["K08","Outros transtornos dos dentes e estruturas de suporte"],
  ["K21","Doença de refluxo gastroesofágico"],
  ["K25","Úlcera gástrica"],
  ["K26","Úlcera duodenal"],
  ["K29","Gastrite e duodenite"],
  ["K29.7","Gastrite não especificada"],
  ["K35","Apendicite aguda"],
  ["K37","Apendicite não especificada"],
  ["K40","Hérnia inguinal"],
  ["K41","Hérnia femoral"],
  ["K42","Hérnia umbilical"],
  ["K43","Hérnia ventral"],
  ["K52","Outras colites e gastroenterites não infecciosas"],
  ["K57","Doença diverticular do intestino"],
  ["K58","Síndrome do intestino irritável"],
  ["K59","Outros transtornos funcionais do intestino"],
  ["K72","Insuficiência hepática"],
  ["K73","Hepatite crônica"],
  ["K74","Fibrose e cirrose hepática"],
  ["K80","Colelitíase"],
  ["K81","Colecistite"],
  ["K85","Pancreatite aguda"],
  ["K86","Outras doenças do pâncreas"],
  ["K92","Outros transtornos do aparelho digestivo"],

  // ── L: Pele ───────────────────────────────────────────────────────────────
  ["L01","Impetigo"],
  ["L02","Abscesso cutâneo, furúnculo e carbúnculo"],
  ["L03","Celulite"],
  ["L04","Linfadenite aguda"],
  ["L20","Dermatite atópica"],
  ["L23","Dermatite de contato alérgica"],
  ["L24","Dermatite de contato irritativa"],
  ["L25","Dermatite de contato não especificada"],
  ["L40","Psoríase"],
  ["L50","Urticária"],
  ["L60","Transtornos das unhas"],
  ["L70","Acne"],
  ["L70.0","Acne vulgar"],

  // ── M: Musculoesquelético ─────────────────────────────────────────────────
  ["M05","Artrite reumatoide soropositiva"],
  ["M10","Gota"],
  ["M15","Poliartrose"],
  ["M16","Coxartrose (artrose do quadril)"],
  ["M17","Gonartrose (artrose do joelho)"],
  ["M19","Outras artroses"],
  ["M23","Transtornos internos do joelho"],
  ["M23.2","Lesão do menisco"],
  ["M47","Espondilose"],
  ["M50","Transtornos dos discos cervicais"],
  ["M51","Outros transtornos de discos intervertebrais"],
  ["M51.1","Hérnia de disco com radiculopatia"],
  ["M54","Dorsalgia"],
  ["M54.2","Cervicalgia"],
  ["M54.3","Ciática"],
  ["M54.4","Lumbociática"],
  ["M54.5","Dor lombar baixa (lombalgia)"],
  ["M54.6","Dor na coluna torácica"],
  ["M65","Sinovite e tenossinovite"],
  ["M65.4","Tenossinovite de De Quervain"],
  ["M70","Transtornos dos tecidos moles relacionados ao uso excessivo"],
  ["M75","Lesões do ombro"],
  ["M75.0","Ombro congelado"],
  ["M75.1","Síndrome do manguito rotador"],
  ["M77","Outras entesopatias"],
  ["M77.0","Epicondilite medial"],
  ["M77.1","Epicondilite lateral (cotovelo de tenista)"],
  ["M79.1","Mialgia"],
  ["M79.7","Fibromialgia"],
  ["M81","Osteoporose sem fratura patológica"],

  // ── N: Gênito-urinário ────────────────────────────────────────────────────
  ["N10","Nefrite tubulointersticial aguda"],
  ["N11","Nefrite tubulointersticial crônica"],
  ["N18","Insuficiência renal crônica"],
  ["N20","Cálculo do rim e do ureter"],
  ["N21","Cálculo do trato urinário inferior"],
  ["N23","Cólica nefrética não especificada"],
  ["N30","Cistite"],
  ["N39","Outros transtornos do trato urinário"],
  ["N39.0","Infecção do trato urinário de localização não especificada"],
  ["N40","Hiperplasia da próstata"],
  ["N41","Doenças inflamatórias da próstata"],
  ["N43","Hidrocele e espermatocele"],
  ["N45","Orquite e epididimite"],
  ["N60","Displasia mamária benigna"],
  ["N70","Salpingite e ooforite"],
  ["N73","Outras doenças inflamatórias pélvicas femininas"],
  ["N75","Doenças da glândula de Bartholin"],
  ["N76","Outras inflamações vaginais e vulvares"],
  ["N80","Endometriose"],
  ["N83","Transtornos não inflamatórios do ovário, da tuba uterina e do ligamento largo"],
  ["N92","Menstruação excessiva, frequente e irregular"],
  ["N94","Dor e outras afecções associadas aos órgãos genitais femininos e ao ciclo menstrual"],
  ["N95","Transtornos menopaúsicos e outros transtornos perimenopáusicos"],

  // ── O: Gravidez, parto e puerpério ──────────────────────────────────────
  ["O00","Gravidez ectópica"],
  ["O10","Hipertensão pré-existente complicando a gravidez"],
  ["O13","Hipertensão gestacional"],
  ["O14","Pré-eclâmpsia"],
  ["O20","Hemorragia do início da gravidez"],
  ["O21","Vômitos excessivos na gravidez"],
  ["O26","Cuidados maternos por outras afecções"],
  ["O28","Resultados anormais do exame de rastreamento pré-natal da mãe"],
  ["O34","Cuidados maternos por anormalidades dos órgãos pélvicos"],
  ["O42","Ruptura prematura de membranas"],
  ["O60","Trabalho de parto prematuro"],
  ["O62","Anormalidades da contração uterina"],
  ["O63","Trabalho de parto prolongado"],
  ["O80","Parto único espontâneo"],
  ["O82","Parto único por cesariana"],
  ["O85","Sepse puerperal"],
  ["O90","Complicações do puerpério"],

  // ── R: Sintomas e sinais ──────────────────────────────────────────────────
  ["R00","Alterações do batimento cardíaco"],
  ["R05","Tosse"],
  ["R06","Alterações da respiração"],
  ["R07","Dor de garganta e no peito"],
  ["R10","Dor abdominal e pélvica"],
  ["R11","Náusea e vômitos"],
  ["R20","Perturbações da sensibilidade cutânea"],
  ["R42","Tontura e instabilidade"],
  ["R50","Febre de outras origens e causas desconhecidas"],
  ["R50.9","Febre não especificada"],
  ["R51","Cefaléia"],
  ["R52","Dor não classificada em outra parte"],
  ["R52.0","Dor aguda"],
  ["R52.2","Outras dores crônicas"],
  ["R53","Mal-estar e fadiga"],
  ["R55","Síncope e colapso"],
  ["R60","Edema não classificado em outra parte"],
  ["R73","Glicemia elevada"],

  // ── S: Lesões traumáticas ─────────────────────────────────────────────────
  ["S00","Traumatismo superficial da cabeça"],
  ["S01","Ferimento da cabeça"],
  ["S02","Fratura do crânio"],
  ["S06","Traumatismo intracraniano"],
  ["S10","Traumatismo superficial do pescoço"],
  ["S12","Fratura do pescoço"],
  ["S13","Luxação, entorse e distensão do pescoço"],
  ["S20","Traumatismo superficial do tórax"],
  ["S22","Fratura de costela, esterno e coluna torácica"],
  ["S30","Traumatismo superficial do abdome, dorso e pelve"],
  ["S32","Fratura da coluna lombar e da pelve"],
  ["S33","Luxação, entorse e distensão lombar"],
  ["S40","Traumatismo superficial do ombro e do braço"],
  ["S42","Fratura do ombro e do braço"],
  ["S43","Luxação, entorse e distensão do ombro"],
  ["S46","Traumatismo de tendão e músculo do ombro"],
  ["S52","Fratura do antebraço"],
  ["S60","Traumatismo superficial do punho e da mão"],
  ["S62","Fratura ao nível do punho e da mão"],
  ["S63","Luxação, entorse e distensão do punho e da mão"],
  ["S70","Traumatismo superficial do quadril e da coxa"],
  ["S72","Fratura do fêmur"],
  ["S80","Traumatismo superficial da perna"],
  ["S82","Fratura da perna, incluindo tornozelo"],
  ["S83","Luxação, entorse e distensão do joelho"],
  ["S90","Traumatismo superficial do tornozelo e do pé"],
  ["S92","Fratura do pé"],
  ["S93","Luxação, entorse e distensão do tornozelo e do pé"],

  // ── T: Outros traumatismos ────────────────────────────────────────────────
  ["T08","Fratura da coluna vertebral não especificada"],
  ["T14","Traumatismo de região não especificada do corpo"],
  ["T14.0","Ferimento superficial de região não especificada"],
  ["T67","Efeitos do calor e da luz"],
  ["T67.0","Insolação"],
  ["T68","Hipotermia"],
  ["T75","Efeitos de outras causas externas"],
  ["T75.2","Efeitos das vibrações"],
  ["T78","Efeitos adversos não classificados em outra parte"],

  // ── Z: Fatores / Ocupacionais ─────────────────────────────────────────────
  ["Z56","Problemas relacionados com o emprego e desemprego"],
  ["Z56.3","Problemas com o horário de trabalho"],
  ["Z56.4","Desacordo com o patrão e colegas de trabalho"],
  ["Z56.5","Condições de trabalho adversas"],
  ["Z56.6","Trabalho por turnos"],
  ["Z57","Exposição a fatores de risco no local de trabalho"],
  ["Z57.0","Exposição ocupacional ao ruído"],
  ["Z57.1","Exposição ocupacional à radiação"],
  ["Z57.2","Exposição ocupacional ao pó"],
  ["Z57.3","Exposição ocupacional a outros contaminantes do ar"],
  ["Z57.4","Exposição ocupacional a agentes tóxicos"],
  ["Z57.6","Exposição ocupacional a temperaturas extremas"],
  ["Z57.7","Exposição a vibração no local de trabalho"],
  ["Z73","Problemas relacionados com organização do modo de vida"],
  ["Z73.0","Sensação de estar acabado (Síndrome de Burnout)"],
  ["Z73.3","Estresse não classificado em outra parte"],
];

/** Busca por código ou descrição (case-insensitive, mínimo 2 caracteres) */
export function buscarCID(termo, max = 10) {
  if (!termo || termo.trim().length < 2) return [];
  const t = termo.toUpperCase().trim();
  const resultados = [];
  for (const [cod, desc] of CID10) {
    if (cod.startsWith(t) || desc.toUpperCase().includes(t)) {
      resultados.push({ cod, desc });
      if (resultados.length >= max) break;
    }
  }
  return resultados;
}

/** Retorna a descrição de um código exato */
export function descCID(codigo) {
  if (!codigo) return "";
  const entry = CID10.find(([cod]) => cod.toUpperCase() === codigo.trim().toUpperCase());
  return entry ? entry[1] : "";
}

/** Valida se o texto tem formato de código CID-10 (ex: A09, B34.9, M54.5) */
export function isCodCID(texto) {
  return /^[A-Za-z]\d{2}(\.\d{1,2})?$/.test((texto || "").trim());
}
