/**
 * Tabela CID-10 — códigos mais relevantes para saúde ocupacional no Brasil
 * Cobre: mental (F), musculoesquelético (M), respiratório (J), circulatório (I),
 * lesões (S/T), neurológico (G), auditivo (H), ocupacional (Z57/Z73)
 */
export const CID10 = [
  // ── F: Transtornos Mentais e Comportamentais ────────────────────────────
  ["F00","Demência na doença de Alzheimer"],
  ["F01","Demência vascular"],
  ["F10","Transtornos mentais e comportamentais pelo uso de álcool"],
  ["F10.1","Uso nocivo de álcool"],
  ["F10.2","Síndrome de dependência do álcool"],
  ["F11","Transtornos pelo uso de opioides"],
  ["F17","Transtornos pelo uso de tabaco"],
  ["F17.1","Uso nocivo do tabaco"],
  ["F17.2","Síndrome de dependência do tabaco"],
  ["F20","Esquizofrenia"],
  ["F31","Transtorno afetivo bipolar"],
  ["F31.0","Transtorno afetivo bipolar, episódio atual hipomaníaco"],
  ["F31.1","Transtorno afetivo bipolar, episódio atual maníaco sem sintomas psicóticos"],
  ["F32","Episódio depressivo"],
  ["F32.0","Episódio depressivo leve"],
  ["F32.1","Episódio depressivo moderado"],
  ["F32.2","Episódio depressivo grave sem sintomas psicóticos"],
  ["F32.3","Episódio depressivo grave com sintomas psicóticos"],
  ["F32.9","Episódio depressivo não especificado"],
  ["F33","Transtorno depressivo recorrente"],
  ["F33.0","Transtorno depressivo recorrente — episódio atual leve"],
  ["F33.1","Transtorno depressivo recorrente — episódio atual moderado"],
  ["F33.2","Transtorno depressivo recorrente — episódio atual grave"],
  ["F40","Transtornos fóbico-ansiosos"],
  ["F41","Outros transtornos ansiosos"],
  ["F41.0","Transtorno de pânico"],
  ["F41.1","Ansiedade generalizada"],
  ["F41.2","Transtorno misto ansioso e depressivo"],
  ["F43","Reações ao estresse grave e transtornos de adaptação"],
  ["F43.0","Reação aguda ao estresse"],
  ["F43.1","Transtorno de estresse pós-traumático"],
  ["F43.2","Transtornos de adaptação"],
  ["F44","Transtornos dissociativos (de conversão)"],
  ["F45","Transtornos somatoformes"],
  ["F48","Outros transtornos neuróticos"],
  ["F48.0","Neurastenia (Burnout/Síndrome de esgotamento)"],
  ["F50","Transtornos alimentares"],
  ["F51","Transtornos do sono não orgânicos"],
  ["F51.0","Insônia não orgânica"],
  ["F60","Transtornos específicos de personalidade"],
  ["F70","Retardo mental leve"],

  // ── G: Doenças do Sistema Nervoso ───────────────────────────────────────
  ["G43","Enxaqueca"],
  ["G44","Outras cefaléias"],
  ["G54","Transtornos das raízes e plexos nervosos"],
  ["G54.1","Transtornos do plexo lombossacral"],
  ["G54.2","Síndrome da raiz cervical (compressão)"],
  ["G54.3","Transtornos da raiz torácica"],
  ["G56","Mononeuropatias do membro superior"],
  ["G56.0","Síndrome do túnel do carpo"],
  ["G56.2","Lesão do nervo ulnar"],
  ["G56.3","Lesão do nervo radial"],
  ["G57","Mononeuropatias do membro inferior"],
  ["G62","Outras polineuropatias"],
  ["G63","Polineuropatia em doenças classificadas em outra parte"],

  // ── H: Doenças do Olho e Ouvido ─────────────────────────────────────────
  ["H25","Catarata senil"],
  ["H52","Distúrbios da refração e da acomodação"],
  ["H60","Otite externa"],
  ["H65","Otite média não-supurativa"],
  ["H72","Perfuração da membrana do tímpano"],
  ["H83","Outras doenças do ouvido interno"],
  ["H83.3","Efeitos de ruído sobre o ouvido (PAIR)"],
  ["H90","Perda de audição por transtorno de condução e neuro-sensorial"],
  ["H91","Outras perdas de audição"],
  ["H91.9","Perda de audição não especificada"],

  // ── I: Doenças do Aparelho Circulatório ─────────────────────────────────
  ["I10","Hipertensão essencial (primária)"],
  ["I11","Doença cardíaca hipertensiva"],
  ["I20","Angina pectoris"],
  ["I20.0","Angina instável"],
  ["I21","Infarto agudo do miocárdio"],
  ["I25","Doença isquêmica crônica do coração"],
  ["I26","Embolia pulmonar"],
  ["I35","Transtornos não reumáticos da valva aórtica"],
  ["I42","Cardiomiopatia"],
  ["I48","Fibrilação e flutter atrial"],
  ["I49","Outras arritmias cardíacas"],
  ["I50","Insuficiência cardíaca"],
  ["I63","Infarto cerebral"],
  ["I64","Acidente vascular cerebral — AVC"],
  ["I70","Aterosclerose"],
  ["I80","Flebite e tromboflebite"],
  ["I83","Varizes dos membros inferiores"],
  ["I84","Hemorroidas"],

  // ── J: Doenças do Aparelho Respiratório ─────────────────────────────────
  ["J00","Nasofaringite aguda (resfriado comum)"],
  ["J01","Sinusite aguda"],
  ["J02","Faringite aguda"],
  ["J03","Amigdalite aguda"],
  ["J04","Laringite e traqueíte agudas"],
  ["J06","Infecções agudas vias aéreas superiores"],
  ["J06.9","Infecção aguda vias aéreas superiores não especificada"],
  ["J10","Gripe devida a vírus da influenza identificado"],
  ["J11","Gripe devida a vírus não identificado"],
  ["J11.0","Pneumonia gripal"],
  ["J11.1","Gripe com outras manifestações respiratórias"],
  ["J18","Pneumonia por microrganismo não especificado"],
  ["J20","Bronquite aguda"],
  ["J30","Rinite alérgica e vasomotora"],
  ["J34","Outros transtornos do nariz e dos seios paranasais"],
  ["J35","Doenças crônicas das amígdalas e adenoides"],
  ["J40","Bronquite não especificada"],
  ["J41","Bronquite crônica simples e mucopurulenta"],
  ["J42","Bronquite crônica não especificada"],
  ["J43","Enfisema"],
  ["J44","Outras doenças pulmonares obstrutivas crônicas — DPOC"],
  ["J45","Asma"],
  ["J45.0","Asma predominantemente alérgica"],
  ["J45.1","Asma não alérgica"],
  ["J45.9","Asma não especificada"],
  ["J60","Pneumoconiose dos mineiros de carvão"],
  ["J61","Pneumoconiose devida ao amianto e a outras fibras minerais"],
  ["J62","Pneumoconiose devida a poeira de sílica"],
  ["J63","Pneumoconiose devida a outros pós inorgânicos"],
  ["J67","Pneumonite de hipersensibilidade devida a poeira orgânica"],
  ["J68","Afecções respiratórias devidas à inalação de produtos químicos"],
  ["J70","Afecções respiratórias devidas a outros agentes externos"],

  // ── K: Doenças do Aparelho Digestivo ────────────────────────────────────
  ["K21","Doença de refluxo gastroesofágico"],
  ["K25","Úlcera gástrica"],
  ["K26","Úlcera duodenal"],
  ["K29","Gastrite e duodenite"],
  ["K35","Apendicite aguda"],
  ["K40","Hérnia inguinal"],
  ["K41","Hérnia femoral"],
  ["K57","Doença diverticular do intestino"],
  ["K80","Colelitíase"],

  // ── L: Doenças da Pele ──────────────────────────────────────────────────
  ["L20","Dermatite atópica"],
  ["L23","Dermatite de contato alérgica"],
  ["L24","Dermatite de contato irritativa"],
  ["L25","Dermatite de contato não especificada"],
  ["L40","Psoríase"],
  ["L50","Urticária"],
  ["L60","Transtornos das unhas"],

  // ── M: Doenças do Sistema Musculoesquelético ────────────────────────────
  ["M00","Artrite piogênica"],
  ["M05","Artrite reumatoide soropositiva"],
  ["M10","Gota"],
  ["M15","Poliartrose"],
  ["M16","Coxartrose (artrose do quadril)"],
  ["M17","Gonartrose (artrose do joelho)"],
  ["M19","Outras artroses"],
  ["M20","Deformidades adquiridas dos dedos das mãos e dos pés"],
  ["M23","Transtornos internos do joelho"],
  ["M23.2","Lesão do menisco"],
  ["M25","Outros transtornos articulares"],
  ["M32","Lúpus eritematoso sistêmico"],
  ["M35","Outras doenças sistêmicas do tecido conjuntivo"],
  ["M40","Cifose e lordose"],
  ["M41","Escoliose"],
  ["M42","Osteocondrose da coluna vertebral"],
  ["M43","Outras dorsopatias deformantes"],
  ["M47","Espondilose"],
  ["M48","Outras espondilopatias"],
  ["M50","Transtornos dos discos cervicais"],
  ["M50.0","Transtorno do disco cervical com mielopatia"],
  ["M50.1","Transtorno do disco cervical com radiculopatia"],
  ["M51","Outros transtornos de discos intervertebrais"],
  ["M51.1","Transtornos de disco lombar e outros com radiculopatia (hérnia de disco)"],
  ["M54","Dorsalgia"],
  ["M54.0","Paniculite afetando regiões do pescoço e dorso"],
  ["M54.1","Radiculopatia"],
  ["M54.2","Cervicalgia"],
  ["M54.3","Ciática"],
  ["M54.4","Lumbociática"],
  ["M54.5","Dor lombar baixa (lombalgia)"],
  ["M54.6","Dor na coluna torácica"],
  ["M54.8","Outras dorsalgias"],
  ["M60","Miosite"],
  ["M62","Outros transtornos musculares"],
  ["M65","Sinovite e tenossinovite"],
  ["M65.0","Tenossinovite estenosante (dedo em gatilho)"],
  ["M65.3","Dedo em gatilho"],
  ["M65.4","Tenossinovite radial estilóide (De Quervain)"],
  ["M70","Transtornos dos tecidos moles relacionados ao uso, uso excessivo e pressão"],
  ["M70.0","Sinovite crônica de mão e pulso"],
  ["M70.1","Bursite da mão"],
  ["M70.2","Bursite do olécrano"],
  ["M70.3","Outras bursites do cotovelo"],
  ["M70.4","Bursite pré-patelar"],
  ["M70.5","Outras bursites do joelho"],
  ["M70.6","Bursite do trocânter"],
  ["M70.7","Outras bursites do quadril"],
  ["M71","Outras bursopatias"],
  ["M75","Lesões do ombro"],
  ["M75.0","Capsulite adesiva do ombro (ombro congelado)"],
  ["M75.1","Síndrome do manguito rotador"],
  ["M75.2","Tendinite bicipital"],
  ["M75.3","Tendinite calcificante do ombro"],
  ["M75.5","Bursite do ombro"],
  ["M76","Entesopatias do membro inferior"],
  ["M77","Outras entesopatias"],
  ["M77.0","Epicondilite medial"],
  ["M77.1","Epicondilite lateral (cotovelo de tenista)"],
  ["M77.2","Periartrite do punho"],
  ["M79","Outros transtornos dos tecidos moles"],
  ["M79.1","Mialgia"],
  ["M79.2","Nevralgia e neurite não especificadas"],
  ["M79.3","Paniculite"],
  ["M79.7","Fibromialgia"],
  ["M80","Osteoporose com fratura patológica"],
  ["M81","Osteoporose sem fratura patológica"],
  ["M85","Outros transtornos da densidade e da estrutura ósseas"],

  // ── N: Doenças do Aparelho Gênito-Urinário ──────────────────────────────
  ["N10","Nefrite tubulointersticial aguda"],
  ["N18","Insuficiência renal crônica"],
  ["N20","Cálculo do rim e do ureter"],
  ["N39","Outros transtornos do trato urinário"],
  ["N39.0","Infecção do trato urinário de localização não especificada"],

  // ── R: Sintomas e Sinais ─────────────────────────────────────────────────
  ["R00","Alterações do batimento cardíaco"],
  ["R03","Medida da pressão arterial"],
  ["R04","Hemorragia das vias respiratórias"],
  ["R05","Tosse"],
  ["R06","Alterações da respiração"],
  ["R07","Dor de garganta e no peito"],
  ["R10","Dor abdominal e pélvica"],
  ["R11","Náusea e vômitos"],
  ["R20","Perturbações da sensibilidade cutânea"],
  ["R25","Movimentos involuntários anormais"],
  ["R33","Retenção urinária"],
  ["R41","Outros sintomas e sinais relativos às funções cognitivas"],
  ["R42","Tontura e instabilidade"],
  ["R51","Cefaléia"],
  ["R52","Dor não classificada em outra parte"],
  ["R52.0","Dor aguda"],
  ["R52.1","Dor crônica intratável"],
  ["R52.2","Outras dores crônicas"],
  ["R53","Mal-estar e fadiga"],
  ["R54","Senilidade"],
  ["R55","Síncope e colapso"],
  ["R60","Edema não classificado em outra parte"],
  ["R73","Glicemia elevada"],

  // ── S: Lesões e Traumatismos da Cabeça/Pescoço/Tronco ──────────────────
  ["S00","Traumatismo superficial da cabeça"],
  ["S01","Ferimento da cabeça"],
  ["S02","Fratura do crânio e dos ossos da face"],
  ["S06","Traumatismo intracraniano"],
  ["S09","Outros traumatismos da cabeça e os não especificados"],
  ["S10","Traumatismo superficial do pescoço"],
  ["S12","Fratura do pescoço"],
  ["S13","Luxação, entorse e distensão das articulações do pescoço"],
  ["S20","Traumatismo superficial do tórax"],
  ["S22","Fratura de costela, esterno e coluna torácica"],
  ["S30","Traumatismo superficial do abdome, dorso e pelve"],
  ["S32","Fratura da coluna lombar e da pelve"],
  ["S33","Luxação, entorse e distensão das articulações da coluna lombar e da pelve"],
  ["S40","Traumatismo superficial do ombro e do braço"],
  ["S41","Ferimento do ombro e do braço"],
  ["S42","Fratura do ombro e do braço"],
  ["S43","Luxação, entorse e distensão do ombro e da cintura escapular"],
  ["S46","Traumatismo de tendão e músculo do ombro"],
  ["S50","Traumatismo superficial do antebraço"],
  ["S52","Fratura do antebraço"],
  ["S60","Traumatismo superficial do punho e da mão"],
  ["S62","Fratura ao nível do punho e da mão"],
  ["S63","Luxação, entorse e distensão das articulações do punho e da mão"],
  ["S70","Traumatismo superficial do quadril e da coxa"],
  ["S72","Fratura do fêmur"],
  ["S80","Traumatismo superficial da perna"],
  ["S82","Fratura da perna, incluindo tornozelo"],
  ["S83","Luxação, entorse e distensão das articulações da perna"],
  ["S90","Traumatismo superficial do tornozelo e do pé"],
  ["S92","Fratura do pé"],
  ["S93","Luxação, entorse e distensão do tornozelo e do pé"],

  // ── T: Traumatismos de causas externas / Intoxicações ───────────────────
  ["T08","Fratura da coluna sem outra especificação"],
  ["T14","Traumatismo de região não especificada do corpo"],
  ["T14.0","Ferimento superficial de região não especificada"],
  ["T14.1","Ferimento de região não especificada"],
  ["T51","Efeito tóxico do álcool"],
  ["T56","Efeito tóxico de metais"],
  ["T57","Efeito tóxico de outras substâncias inorgânicas"],
  ["T58","Efeito tóxico do monóxido de carbono"],
  ["T59","Efeito tóxico de outros gases, fumaças e vapores"],
  ["T60","Efeito tóxico de pesticidas"],
  ["T65","Efeito tóxico de outras substâncias e as não especificadas"],
  ["T67","Efeitos do calor e da luz"],
  ["T67.0","Insolação"],
  ["T68","Hipotermia"],
  ["T70","Efeitos da pressão"],
  ["T70.2","Outros efeitos e os não especificados da altitude elevada"],
  ["T73","Efeitos de privação"],
  ["T75","Efeitos de outras causas externas"],
  ["T75.0","Efeitos do relâmpago"],
  ["T75.1","Afogamento e submersão não fatal"],
  ["T75.2","Efeitos das vibrações"],
  ["T75.3","Doença do movimento (cinetose)"],
  ["T78","Efeitos adversos não classificados em outra parte"],
  ["T79","Certas complicações precoces de traumatismos"],

  // ── Z: Fatores que influenciam o estado de saúde / Ocupacionais ─────────
  ["Z55","Problemas relacionados com a educação e com a alfabetização"],
  ["Z56","Problemas relacionados com o emprego e desemprego"],
  ["Z56.0","Desemprego não especificado"],
  ["Z56.1","Mudança de emprego"],
  ["Z56.3","Problemas com o horário de trabalho"],
  ["Z56.4","Desacordo com o patrão e colegas de trabalho"],
  ["Z56.5","Condições de trabalho adversas"],
  ["Z56.6","Trabalho por turnos"],
  ["Z57","Exposição a fatores de risco no local de trabalho"],
  ["Z57.0","Exposição ocupacional ao ruído"],
  ["Z57.1","Exposição ocupacional à radiação"],
  ["Z57.2","Exposição ocupacional ao pó"],
  ["Z57.3","Exposição ocupacional a outros contaminantes do ar"],
  ["Z57.4","Exposição ocupacional a agentes tóxicos no local de trabalho"],
  ["Z57.5","Exposição ocupacional a agentes tóxicos em outras indústrias"],
  ["Z57.6","Exposição ocupacional a temperaturas extremas"],
  ["Z57.7","Exposição a vibração no local de trabalho"],
  ["Z57.8","Exposição a outros fatores de risco no trabalho"],
  ["Z58","Problemas relacionados ao ambiente físico"],
  ["Z63","Outros problemas relacionados com grupo de apoio primário"],
  ["Z71","Pessoas que procuram os serviços de saúde para orientação"],
  ["Z73","Problemas relacionados com organização do modo de vida"],
  ["Z73.0","Sensação de estar acabado (Síndrome de Burnout)"],
  ["Z73.1","Acentuação de traços de personalidade"],
  ["Z73.2","Falta de repouso e de lazer"],
  ["Z73.3","Estresse não classificado em outra parte"],
  ["Z73.6","Limitação de atividades devida a incapacidade"],
  ["Z76","Pessoas que procuram os serviços de saúde em outras circunstâncias"],
];

/** Busca rápida por código ou descrição (case-insensitive) */
export function buscarCID(termo, max = 10) {
  if (!termo || termo.trim().length < 2) return [];
  const t = termo.toUpperCase().trim();
  const resultados = [];

  for (const [cod, desc] of CID10) {
    if (cod.startsWith(t) || desc.toUpperCase().includes(t)) {
      resultados.push({ cod, desc });
      if (resultados.length >= max) break;
    }
  }
  return resultados;
}

/** Retorna a descrição de um código exato */
export function descCID(codigo) {
  const entry = CID10.find(([cod]) => cod.toUpperCase() === (codigo || "").toUpperCase());
  return entry ? entry[1] : "";
}
